FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY login.html /usr/share/nginx/html/login.html
COPY profile.html /usr/share/nginx/html/profile.html
COPY admin.html /usr/share/nginx/html/admin.html
COPY asset.html /usr/share/nginx/html/asset.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY auth.js /usr/share/nginx/html/auth.js
COPY app.js /usr/share/nginx/html/app.js
COPY asset.js /usr/share/nginx/html/asset.js
COPY login.js /usr/share/nginx/html/login.js
COPY profile.js /usr/share/nginx/html/profile.js
COPY admin.js /usr/share/nginx/html/admin.js
